---
- name: restore initramfs.conf
  copy:
    src: /etc/initramfs-tools/initramfs.conf~
    dest: /etc/initramfs-tools/initramfs.conf
    remote_src: yes
  when: is_chroot

- name: remove backup file
  file:
    path: /etc/initramfs-tools/initramfs.conf~
    state: absent
  when: is_chroot
